name: doc
image:
  repository: registry.gitlab.com/tradalab/redishub/doc
  tag: prod-7276ce8 # CI overwrites this line
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: gitlab-cred
replicas: 1
container:
  command: [] # use the image's default CMD (node server.js)
  args: []
  port: 6100
service:
  enabled: true
  port: 6100
resources: null
config:
  enabled: false
infisical:
  enabled: false
migrate:
  enabled: false
ingress:
  enabled: true
  host: redishub.tradalab.com
  pathPrefix: ""
  priority: 0
  tlsSecretName: redishub-tradalab-com-tls
  redirect: true
certificate:
  enabled: true
  host: redishub.tradalab.com
  secretName: redishub-tradalab-com-tls
  issuerName: letsencrypt-prod
  issuerKind: ClusterIssuer
